from typing import Any, Iterator

class CujsonError(Exception): ...
class InvalidUtf8Error(CujsonError, ValueError): ...
class UnbalancedError(CujsonError, ValueError): ...
class InputError(CujsonError, ValueError): ...
class CudaError(CujsonError, RuntimeError): ...
class NoDeviceError(CudaError): ...

class Document:
    def to_python(self) -> Any: ...
    def pointer(self, pointer: str) -> Any: ...
    def lines(self) -> list[Any]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...

def cuda_info() -> dict[str, Any]: ...
def parse(data: bytes | bytearray | memoryview | str) -> Document: ...
def parse_file(path: str) -> Document: ...
def parse_lines(
    data: bytes | bytearray | memoryview | str, chunk_bytes: int = ...
) -> Document: ...
